- name: reload ufw
  command: ufw reload
  async: 10
  poll: 0

- name: reconfigure gitlab
  command: gitlab-ctl reconfigure
  async: 1200
  poll: 10

- name: reconfigure gitlab
  command: gitlab-ctl reconfigure
  become: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted