- name: Verify SSM connectivity
  wait_for_connection:
    timeout: 300

- name: Ensure /captain directory exists
  file:
    path: /captain
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  become: true


- name: Initialize Docker Swarm if needed
  command: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
  when: 
    - swarm_state.stdout | trim != 'active'
    - not caprover_data_exists
  become: true
  register: swarm_init
  changed_when: swarm_init.rc == 0
  failed_when: swarm_init.rc != 0 and "already part of a swarm" not in swarm_init.stderr

- name: Install required Python libraries for Docker.
  apt:
    name:
      - docker
      - docker-compose
    state: present

- name: Ensure Docker is running
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: true
  when: not caprover_data_exists

- name: Gather package facts
  package_facts:
    manager: auto

- name: Configure firewall
  shell: |
    ufw allow 80,443,3000,996,7946,4789,2377/tcp
    ufw allow 7946,4789,2377/udp
    ufw --force enable
  become: true

- name: Install Docker
  block:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true
      become: true
      


    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      become: true

    - name: Install Docker components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: true
      when: (ansible_facts.packages is not defined) or ('docker-ce' not in ansible_facts.packages)

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true
      become: true

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      become: true
  when: "'docker' not in ansible_facts.packages"

- name: Install CapRover
  docker_container:
    name: caprover
    image: caprover/caprover:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/captain:/captain"
    env:
      ACCEPTED_TERMS: "true"
      MAIN_NODE_IP_ADDRESS='127.0.0.1'

  become: true

- name: Wait for CapRover initialization
  wait_for:
    port: 3000
    delay: 10
    timeout: 300
  become: true

- name: Set CapRover password
  shell: |
    HASH=$(docker exec caprover node /usr/src/app/node_modules/bcryptjs/bin/bcrypt {{ vault_caprover_password }})
    sed -i "s/\"hashedPassword\":.*/\"hashedPassword\": \"$HASH\"/" /captain/data/config-captain.json
  become: true

- name: Restart CapRover container..
  docker_container:
    name: caprover
    state: started
    restart: yes
  become: true

- name: Verify CapRover API health
  uri:
    url: http://localhost:3000/api/v2/health
    status_code: 200
    timeout: 10
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  become: true

- name: Check Docker containers
  command: docker ps
  register: docker_containers
  become: true

- name: Display Docker containers
  debug:
    var: docker_containers.stdout_lines

- name: Check CapRover logs
  command: docker logs caprover --tail 50
  register: caprover_logs
  become: true

- name: Display CapRover logs
  debug:
    var: caprover_logs.stdout_lines