# ansible/roles/caprover/tasks/main.yaml
---
- name: Set Python interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python3.8

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
      - ufw
    state: present
    update_cache: yes

- name: Add Node.js repository
  shell: |
    curl -sL https://deb.nodesource.com/setup_18.x | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ensure Docker is started
  systemd:
    name: docker
    state: started
    enabled: true

- name: Allow CapRover ports in UFW
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: 80, proto: tcp }
    - { port: 443, proto: tcp }
    - { port: 3000, proto: tcp }
    - { port: 996, proto: tcp }
    - { port: 7946, proto: tcp }
    - { port: 7946, proto: udp }
    - { port: 4789, proto: udp }
    - { port: 2377, proto: tcp }
  when: ansible_os_family == "Debian"

- name: Enable UFW
  ufw:
    state: enabled
    policy: allow

- name: Run CapRover container
  docker_container:
    name: caprover
    image: caprover/caprover
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "996:996"
      - "7946:7946"
      - "4789:4789"
      - "2377:2377"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /captain:/captain
    env:
      CAPROVER_ROOT_PASSWORD: "{{ vault_caprover_password }}"
      CAPROVER_ROOT_DOMAIN: "{{ domain_name }}"
      ACCEPTED_TERMS: "true"
      MAIN_NODE_IP_ADDRESS: "{{ ansible_host }}"
      BY_PASS_PROXY_CHECK: 'TRUE'
    restart_policy: always
    state: started

- name: Install CapRover CLI
  npm:
    name: caprover
    global: yes
    state: present

- name: Configure CapRover dashboard to use subdomain
  command: caprover serversetup --caproverUrl http://captain.{{ domain_name }}
  args:
    creates: /captain/data/config-captain.json

- name: Verify CapRover installation
  shell: |
    curl -sI http://localhost:3000 | grep "200 OK"
  register: result
  until: result.rc == 0
  retries: 10
  delay: 30

- name: Allow VPC CIDR in UFW
  ufw:
    rule: allow
    src: "{{ vpc_cidr }}" 