- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
    state: present
    update_cache: true

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ensure Docker is started
  systemd:
    name: docker
    state: started
    enabled: true

- name: Run CapRover container
  docker_container:
    name: caprover
    image: caprover/caprover
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /captain:/captain
    env:
      CAPROVER_ROOT_PASSWORD: "{{ vault_caprover_password }}"
      CAPROVER_ROOT_DOMAIN: "{{ domain_name }}"
    restart_policy: always

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Install CapRover CLI
  npm:
    name: caprover
    global: true

- name: Configure CapRover dashboard to use subdomain
  command: caprover serversetup --caproverUrl http://captain.{{ domain_name }}:3000
  args:
    creates: /captain/data/config-captain.json
