- hosts: caprover
  vars_files:
    - vault.yml
  become: true
  connection: community.aws.aws_ssm
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssm_executable: /usr/bin/session-manager-plugin
    ansible_ssm_region: eu-north-1
  roles:
    - caprover

- hosts: gitlab
  vars_files:
    - vault.yml
  become: true
  connection: community.aws.aws_ssm
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssm_executable: /usr/bin/session-manager-plugin
    ansible_ssm_region: eu-north-1
  roles:
    - gitlab