- hosts: caprover
  vars_files:
    - vault.yml
  become: true
  connection: aws_ssm
  roles:
    - caprover

- hosts: gitlab
  vars_files:
    - vault.yml
  become: true
  connection: aws_ssm
  roles:
    - gitlab