- hosts: caprover
  connection: community.aws.aws_ssm
  vars_files:
    - vault.yml
  become: true
  roles:
    - caprover

- hosts: gitlab
  connection: community.aws.aws_ssm
  vars_files:
    - vault.yml
  become: true
  roles:
    - gitlab