name: Terraform Destroy

on:
  workflow_dispatch:
  
jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform Variables
        run: |
          # Format allowed_ips as proper Terraform list
          IPS_STRING=$(echo '${{ secrets.ALLOWED_IPS }}' | sed "s/,/\", \"/g")
          echo "allowed_ips = [\"$IPS_STRING\"]" > secrets.auto.tfvars
          echo "certificate_arn = \"${{ secrets.ACM_CERTIFICATE_ARN }}\"" >> secrets.auto.tfvars
          echo "domain_name = \"${{ secrets.DOMAIN_NAME }}\"" >> secrets.auto.tfvars
          echo "Generated secrets.auto.tfvars:"
          cat secrets.auto.tfvars

      - name: Add Explicit Backend Block
        run: |
          cat <<EOF >> backend.tf
          terraform {
            backend "s3" {}
          }
          EOF
          cat backend.tf

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main'
        run: |
          terraform destroy -target module.alb.aws_lb_listener_rule \
          -target module.alb.aws_lb_listener \
          -auto-approve
          sleep 30  # Wait for rules to detach
          terraform destroy -auto-approve