name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform Variables
        run: |
          # Format allowed_ips as proper Terraform list
          IPS_STRING=$(echo '${{ secrets.ALLOWED_IPS }}' | sed "s/,/\", \"/g")
          echo "allowed_ips = [\"$IPS_STRING\"]" > secrets.auto.tfvars
          echo "certificate_arn = \"${{ secrets.ACM_CERTIFICATE_ARN }}\"" >> secrets.auto.tfvars
          echo "domain_name = \"${{ secrets.DOMAIN_NAME }}\"" >> secrets.auto.tfvars
          echo "Generated secrets.auto.tfvars:"
          cat secrets.auto.tfvars

      - name: Add Explicit Backend Block
        run: |
          cat <<EOF >> backend.tf
          terraform {
            backend "s3" {}
          }
          EOF
          cat backend.tf

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Format Check
        run: |
          terraform fmt
          echo "Format check completed successfully"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      # FIXED INDENTATION HERE
      - name: Save Terraform Outputs
        if: github.ref == 'refs/heads/main'
        run: |
          # Get outputs and trim any whitespace
          CAPROVER_IP=$(terraform output -raw caprover_instance_ip | tr -d '\n')
          GITLAB_IP=$(terraform output -raw gitlab_instance_ip | tr -d '\n')
          
          # Set environment variables
          echo "CAPROVER_IP=$CAPROVER_IP" >> $GITHUB_ENV
          echo "GITLAB_IP=$GITLAB_IP" >> $GITHUB_ENV
          
          # Debug outputs
          echo "Debug: CAPROVER_IP: $CAPROVER_IP"
          echo "Debug: GITLAB_IP: $GITLAB_IP"

      # FIXED TO USE ENVIRONMENT VARIABLES DIRECTLY
      - name: Create Ansible Inventory
        if: github.ref == 'refs/heads/main'
        working-directory: ansible
        run: |
          echo "[caprover]" > inventory.ini
          echo "${{ env.CAPROVER_IP }}" >> inventory.ini
          echo "[gitlab]" >> inventory.ini
          echo "${{ env.GITLAB_IP }}" >> inventory.ini
          # Debug inventory
          cat inventory.ini

      - name: Setup SSH Configuration
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.CAPROVER_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ env.GITLAB_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible Configuration
        if: github.ref == 'refs/heads/main'
        working-directory: ansible
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          chmod 600 .vault_pass
          ansible-playbook -i inventory.ini playbooks/caprover.yml \
            --extra-vars "domain_name=${{ secrets.DOMAIN_NAME }}" \
            --vault-password-file .vault_pass
          ansible-playbook -i inventory.ini playbooks/gitlab.yml \
            --extra-vars "vault_gitlab_root_password='${{ secrets.GITLAB_ROOT_PASSWORD }}'" \
            --vault-password-file .vault_pass
          rm .vault_pass
